// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zevsecacnbclliebdpru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpldnNlY2FjbmJjbGxpZWJkcHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NDk2MjYsImV4cCI6MjA4OTUyNTYyNn0.izp36_yYg7NRX0uEqg6PLOUsKymZJmUXzh1AfFLH8nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});